### ISSUE TITLE
alembic is not using APP_CONFIG_FILE

### ISSUE THREAD

**Issue by nmiletic** [rhoboro/async-fastapi-sqlalchemy#9]
It seems that alembic is not using APP_CONFIG_FILE variable but just using what is in alembic.ini. Since APP_CONFIG_FILE is set when calling alembic in documentation I am not sure if this was intended?

**Comment by rhoboro** [comment]
Thank you for the comment!!
Originally, I was going to change the target database depending on the APP_CONFIG_FILE. 
Thus, I have fixed this bug on #10 .
